repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

templates: 
  default: &default
    namespace: backbone
    missingFileHandler: Warn

values:
  - ../environments/env-secrets.yaml
  - ../environments/env.yaml

releases:
- name: cert-manager
  chart: ./cert-manager
  namespace: egov
  installed: false
  version: v1.13.3
  disableValidation: true
  values:
    - ./cert-manager/values.yaml

- name: postgresql
  installed: true
  chart: ./postgresql
  version: 10.16.3
  <<: *default
  values:
    - ./postgresql/values.yaml
    - global:
        postgresql:
          postgresqlPassword: {{ .Values.secrets.db.password | quote }}
            
- name: redis
  installed: true
  chart: ./redis
  version: 7.2.4
  <<: *default
  values:
    - ./redis/values.yaml

- name: elasticsearch
  installed: true
  chart: ./elasticsearch
  version: 8.11.3
  <<: *default
  values:
    - ./elasticsearch/values.yaml
    - secret:
        password: {{ .Values.secrets.elasticsearch.password }}

- name: elasticsearch-data
  installed: true
  chart: ./elasticsearch-data
  version: 8.11.3
  <<: *default
  values:
    - ./elasticsearch-data/values.yaml

- name: kibana
  installed: true
  chart: ./kibana
  version: 8.11.3
  force: true
  <<: *default
  values:
    - ./kibana/values.yaml
    - ingress:
        hosts:
          - host: {{ .Values.global.domain }}
            paths:
              - path: /kibana
        tls: 
          - secretName: {{ .Values.global.domain }}-tls-certs
            hosts:
              - {{ .Values.global.domain }}

- name: kafka-kraft
  installed: true
  chart: ./kafka-kraft
  version: 26.2.0
  <<: *default
  values:
    - ./kafka-kraft/values.yaml
  set:
    - name: kraft.clusterId
      value: {{ .Values.secrets.kafka.clusterID }}

- name: ingress-nginx
  installed: false
  chart: ./ingress-nginx
  version: 4.10.0
  <<: *default
  values:
    - ./ingress-nginx/values.yaml
    - domain: {{ .Values.global.domain }}

- name: playground
  installed: true
  chart: ./playground
  version: 0.1.0
  <<: *default
  values:
    - ./playground/values.yaml
