apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: kafka-scc
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: true
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users: []
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
seccompProfiles:
- "runtime/default"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafka-scc
  namespace: backbone
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - kafka-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kafka-scc
  namespace: backbone
subjects:
  - kind: ServiceAccount
    name: kafka-kraft
    namespace: backbone
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kafka-scc
